=== rhmg/website/App_Data/Photosets/PhotoSets.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="PhotoSets"
    targetNamespace="http://www.rhmg.co.uk"
    elementFormDefault="qualified"
    xmlns="http://www.rhmg.co.uk"
    xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Pictures">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Picture" maxOccurs="unbounded" minOccurs="1">
          <xs:complexType>
            <xs:attribute name="index" type="xs:int" use="required"></xs:attribute>
            <xs:attribute name="filename" type="xs:string" use="required"></xs:attribute>
            <xs:attribute name="tooltip" type="xs:string" use="required"></xs:attribute>
            <xs:attribute name="text" type="xs:string" use="required"></xs:attribute>
            <xs:attribute name="pageDescription" type="xs:string" use="optional"></xs:attribute>
            <xs:attribute name="dateTaken" type="xs:string" use="required"></xs:attribute>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="length" type="xs:int" use="required"></xs:attribute>
      <xs:attribute name="photopath" type="xs:string" use="required"></xs:attribute>
      <xs:attribute name="pageTitle" type="xs:string" use="required"></xs:attribute>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== rhmg/website/bin/Xml/BuildTheStudio.xml
<?xml version="1.0" encoding="utf-8" ?>
<Pictures
  xmlns="http://www.rhmg.co.uk"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.rhmg.co.uk PhotoSets.xsd"
  length="22"
  photopath="~/images/photos/making_of/">
  <Picture index="1"
           filename="1 Rock Hard Studios - The empty unit"
           tooltip="Rock Hard Studios - The empty unit"
           text="This picture was taken while we were searching for a unit in which to build the studio. The previous occupants had left it in quite a bad state."
           pageDescription=""
           dateTaken="2nd December 2006"/>
  <Picture index="2"
           filename="2 Rock Hard Studios - Clearing and drying the unit"
           tooltip="Rock Hard Studios - Clearing and drying the unit"
           text="Taken quite soon after we had been given the keys, you can see that we had already taken most of the unnecessary mezzanine down. Also notice at the bottom of the upright, our little camping stove."
           pageDescription=""
           dateTaken="25th February 2007"/>
  <Picture index="3"
           filename="3 Rock Hard Studios - taking down the old mezzanine"
           tooltip="Rock Hard Studios - taking down the old mezzanine"
           text="Once again taken on one of the early days. The fake leather sofa had been left in the unit. Honest"
           pageDescription=""
           dateTaken="25th February 2007"/>
  <Picture index="4"
           filename="4 Rock Hard Studios - Looking up the unit"
           tooltip="Rock Hard Studios - Looking up the unit"
           text="A view from by the shutters. The last cross piece had to be lifted off by a fork-lift (thanks Stuff-it!) as it was SO heavy."
           pageDescription=""
           dateTaken="25th February 2007"/>
  <Picture index="5"
           filename="5 Rock Hard Studios - Phil teaching Dan how to lay bricks"
           tooltip="Rock Hard Studios - Phil teaching Dan how to lay bricks"
           text="The first wall of Rock Hard Studios. Dan is shown here learning how to build a straight wall - if only he'd listened."
           pageDescription=""
           dateTaken="28th February 2007"/>
  <Picture index="6"
           filename="6 Rock Hard Studios - Room 4 taking shape"
           tooltip="Rock Hard Studios - Room 4 taking shape"
           text="A view from by the shutters. In the back right corner you can see the beginnings of Room 4."
           pageDescription=""
           dateTaken="28th February 2007"/>
  <Picture index="7"
           filename="7 Rock Hard Studios - Working on getting electricity"
           tooltip="Rock Hard Studios - Working on getting electricity"
           text="Dan on the roof of the entrance hall, fitting the main electricity armoured cables. The old office has been completely removed and the space is ready for the Control Room."
           pageDescription=""
           dateTaken="10th March 2007"/>
  <Picture index="8"
           filename="8 Rock Hard Studios - Team work while building the Chill Out Room"
           tooltip="Rock Hard Studios - Team work while building the Chill Out Room"
           text="The crew helping to lift the large outer wall of the Chill Out Room into position. From left to right: Dick Smith, Chris Hilton, Ste Picton, Dan Atkinson, Andrew Cox, Paul Higham"
           pageDescription=""
           dateTaken="13th March 2007"/>
  <Picture index="9"
           filename="9 Rock Hard Studios - Rooms 3 and 4 taking shape"
           tooltip="Rock Hard Studios - Rooms 3 and 4 taking shape"
           text="A view across the unit. Rooms 3 and 4 have had all their block-work done and they are close to completion."
           pageDescription=""
           dateTaken="21st March 2007"/>
  <Picture index="10"
           filename="10 Rock Hard Studios - Looking back down the unit"
           tooltip="Rock Hard Studios - Looking back down the unit"
           text="Looking back down the unit from by the fire-exit. The large wooden box in the foreground was full of scented wax. Strange."
           pageDescription=""
           dateTaken="21st March 2007"/>
  <Picture index="11"
           filename="11 Rock Hard Studios - Room 4 all shiny and new"
           tooltip="Rock Hard Studios - Room 4 all shiny and new"
           text="The completed Room 4 Rehearsal Room. The last time it would ever look so clean and tidy."
           pageDescription=""
           dateTaken="29th March 2007"/>
  <Picture index="12"
           filename="12 Rock Hard Studios - Starting to build the Live Room"
           tooltip="Rock Hard Studios - Starting to build the Live Room"
           text="Starting to lay Block for the Live Room. Slowly the shape of the studio is forming."
           pageDescription=""
           dateTaken="14th May 2008"/>
  <Picture index="13"
           filename="13 Rock Hard Studios - The Live Room taking shape"
           tooltip="Rock Hard Studios - The Live Room taking shape"
           text="This is taken inside the Live Room while the block work was being completed. Note the speaker cabinets back left of the room - the old scaffolding... scary."
           pageDescription=""
           dateTaken="20th November 2008"/>
  <Picture index="14"
           filename="14 Rock Hard Studios - Studding the walls of the Live Room"
           tooltip="Rock Hard Studios - Studding the walls of the Live Room"
           text="Looking down into the new Live Room from the window into the Chill Out Room. Here we are putting the stud work onto the walls."
           pageDescription=""
           dateTaken="19th January 2009"/>
  <Picture index="15"
           filename="15 Rock Hard Studios - The plaster board goes on in the Live Room"
           tooltip="Rock Hard Studios - The plaster board goes on in the Live Room"
           text="Taking a look across the Live Room as the plaster board goes up and the joint strips are put in place."
           pageDescription=""
           dateTaken="3rd February 2009"/>
  <Picture index="16"
           filename="16 Rock Hard Studios - Installing lights in the Live Room"
           tooltip="Rock Hard Studios - Installing lights in the Live Room"
           text="The lights being installed in the Live Room, and cladding going on round the edges."
           pageDescription=""
           dateTaken="15th February 2009"/>
  <Picture index="17"
           filename="17 Rock Hard Studios - Finishing touches to the Live Room"
           tooltip="Rock Hard Studios - Finishing touches to the Live Room"
           text="The finishing touches being applied to the Live Room including painting the doors and fitting the cladding."
           pageDescription=""
           dateTaken="15th February 2009"/>
  <Picture index="18"
           filename="18 Rock Hard Studios - The Live Room in all its glory"
           tooltip="Rock Hard Studios - The Live Room in all its glory"
           text="The finished live room set up, having tested the sound with a drum kit and some loud guitar."
           pageDescription=""
           dateTaken="20th February 2009"/>
  <Picture index="19"
           filename="19 Rock Hard Studios - Room 2 ready for a band"
           tooltip="Rock Hard Studios - Room 2 ready for a band"
           text="Room 2 all set up and ready for a band.  Note the Sonor drum kit and monitor wedges."
           pageDescription=""
           dateTaken="10th May 2009"/>
  <Picture index="20"
           filename="20 Rock Hard Studios - Starting to clear the common areas"
           tooltip="Rock Hard Studios - Starting to clear the common areas"
           text="The beginning of the process to finish the common areas. The old partition walls have been removed ready for being replaced by blockwork."
           pageDescription=""
           dateTaken="4th August 2009"/>
  <Picture index="21"
           filename="21 Rock Hard Studios - Rambo looking through the wall"
           tooltip="Rock Hard Studios - Rambo looking through the wall"
           text="Rambo looking through the hole in the wall left by the old boiler. Shortly after this picture was taken, the hole was filled in."
           pageDescription=""
           dateTaken="6th August 2009"/>
  <Picture index="22"
           filename="22 Rock Hard Studios - The entrance and corridor takes shape"
           tooltip="Rock Hard Studios - The entrance and corridor takes shape"
           text="Blockwork being built along the corridor and by the kitchen. The wall on the right is for Room 1."
           pageDescription=""
           dateTaken="12th August 2009"/>
</Pictures>

=== rhmg/website/Xml/RecordingTheSilvertones.xml
<?xml version="1.0" encoding="utf-8" ?>
<Pictures
  xmlns="http://www.rhmg.co.uk"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.rhmg.co.uk PhotoSets.xsd"
  length="14"
  photopath="~/images/photos/silvertones_session/"
  pageTitle="Silvertones Session 15th - 17th Jan 2010">
  <Picture index="1"
           filename="Silvertones recording their album at Rock Hard Studios - the view from the Chill Out Room"
           tooltip="Silvertones recording their album at Rock Hard Studios - the view from the Chill Out Room"
           text="This is a view of the Silvertones recording backing tracks to their new album. This picture taken from the window into the Chill Out Room upstairs."
           pageDescription=""
           dateTaken="15th January 2010"/>
  <Picture index="2"
           filename="Billy singing guide vocals while laying down backing tracks for the Silvertones at Rock Hard Studios"
           tooltip="Billy singing guide vocals while laying down backing tracks for the Silvertones at Rock Hard Studios"
           text="A close up photograph of Matt singing a backing track guide vocal.  He can hear a click tracks, and the instruments, through his headphones."
           pageDescription=""
           dateTaken="15th January 2010"/>
  <Picture index="3"
           filename="Dan recording drums for the Silvertones at Rock Hard Studios"
           tooltip="Dan recording drums for the Silvertones at Rock Hard Studios"
           text="Dan playing along to the click track and recording the drums - he is totally enclosed by sound baffles to improve the quality of the recording."
           pageDescription=""
           dateTaken="15th January 2010"/>
  <Picture index="4"
           filename="Andrew and Dan discussing the sounds during the Silvertones session at Rock Hard Studios"
           tooltip="Andrew and Dan discussing the sounds during the Silvertones session at Rock Hard Studios"
           text="Andrew and Dan discussing the finer points of the on-tape sound.  Ever since they first started working together these two have found they are an excellent team behind a mixing desk."
           pageDescription=""
           dateTaken="15th January 2010"/>
  <Picture index="5"
           filename="Tom recording guitar for the Silvertones at Rock Hard Studios"
           tooltip="Tom recording guitar for the Silvertones at Rock Hard Studios"
           text="Tom playing a guide lead guitar part in the Live Room."
           pageDescription=""
           dateTaken="15th January 2010"/>
  <Picture index="6"
           filename="Billy laying down rhythm guitar during the Silvertones recording session at Rock Hard Studios"
           tooltip="Billy laying down rhythm guitar during the Silvertones recording session at Rock Hard Studios"
           text="Billy playing rhythm guitar guide parts. Piled up next to him are a couple of our amplifiers that we use here. His amp is down the corridor in Room 4 Isolation Room."
           pageDescription=""
           dateTaken="15th January 2010"/>
  <Picture index="7"
           filename="Billy and Tom leaving the Live Room after a successful take at Rock Hard Studios"
           tooltip="Billy and Tom leaving the Live Room after a successful take at Rock Hard Studios"
           text="Matt and Tom walking from the Live Room into the Control Room to listen back to a take."
           pageDescription=""
           dateTaken="15th January 2010"/>
  <Picture index="8"
           filename="Anders in the groove playing the bass line to a Silvertones song while recording at Rock Hard Studios"
           tooltip="Anders in the groove playing the bass line to a Silvertones song while recording at Rock Hard Studios"
           text="Anders concentrating on keeping a groove and being in time.  Note his right foot: mid-tap. This is always a good idea when recording as if you are tapping your foot to the tempo you will find it easier to stay in time."
           pageDescription=""
           dateTaken="15th January 2010"/>
  <Picture index="9"
           filename="The Silvertones and Management sitting in the Control Room listening to a mix at Rock Hard Studios"
           tooltip="The Silvertones and Management sitting in the Control Room listening to a mix at Rock Hard Studios"
           text="Relaxing in the Control Room listening back to the days work. It has been a long day, but successful. Left to Right: Matt, Tom, Chris, Dave, Anders and Dan."
           pageDescription=""
           dateTaken="15th January 2010"/>
  <Picture index="10"
           filename="Dan focussed on keeping to the click while recording Silvertones songs at Rock Hard Studios"
           tooltip="Dan focussed on keeping to the click while recording Silvertones songs at Rock Hard Studios"
           text="Day two and Dan is back in the zone laying down a solid drum track.  For this session we used a total of 14 microphones on the kit, doubling up on cymbals and toms to enable us to get a large variety of sounds which we can then pick from during the mixing phase."
           pageDescription=""
           dateTaken="16th January 2010"/>
  <Picture index="11"
           filename="Taking a breath of fresh air during the Silvertones recording session"
           tooltip="Taking a breath of fresh air during the Silvertones recording session"
           text="This photograph is taken looking out through the shutters from inside the studio. Taking fresh air regularly is important in sessions as it helps you focus. Rambo (the studio guard dog) looks on hopefully."
           pageDescription=""
           dateTaken="16th January 2010"/>
  <Picture index="12"
           filename="Andrew deep in thought whilst recording Silvertones backing tracks at Rock Hard Studios"
           tooltip="Andrew deep in thought whilst recording Silvertones backing tracks at Rock Hard Studios"
           text="Andrew focussing on the music while control the headphone mix for the band.  It is important at all times to focus on timing, as this is an equal part to good music along side melody."
           pageDescription=""
           dateTaken="16th January 2010"/>
  <Picture index="13"
           filename="Tom doing lead guitar overdubs on Silvertones songs at Rock Hard Studios"
           tooltip="Tom doing lead guitar overdubs on Silvertones songs at Rock Hard Studios"
           text="Tom laying down his guitar parts. He is able to sit in the control room to do this which helps him to play along with the actual mix and also be in a controlled physical environment."
           pageDescription=""
           dateTaken="16th January 2010"/>
  <Picture index="14"
           filename="Billy in the Live Room recording backing tracks for the Silvertones at Rock Hard Studios"
           tooltip="Billy in the Live Room recording backing tracks for the Silvertones at Rock Hard Studios"
           text="Matt in the live room, showing the second floor window into the Chill Out Room. This pictures gives you a good idea of the space that we have here at Rock Hard Studios."
           pageDescription=""
           dateTaken="16th January 2010"/>
</Pictures>

=== rhmg/website/App_Data/Photosets/PostImprovements.xml
<?xml version="1.0" encoding="utf-8" ?>
<Pictures
  xmlns="http://www.rhmg.co.uk"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.rhmg.co.uk PhotoSets.xsd"
  length="13"
  photopath="~/images/photos/post_improvements/"
  pageTitle="Studio After Improvements">
  <Picture index="1"
           filename="Rock Hard Studios Blackpool The Corridor Showing Kitchen Control Room Live Room and Room 4"
           tooltip="Rock Hard Studios - The Corridor Showing Kitchen Control Room Live Room and Room 4"
           text="The view that now welcomes you to Rock Hard Studios with comfy sofa and the clearly labelled doors for our facilities."
           pageDescription=""
           dateTaken="11 January 2011"/>
  <Picture index="2"
           filename="Rock Hard Studios Highly Welcoming Entrance Area With Comfy Sofa With Rehearsal and Recording Spaces Leading Off"
           tooltip="Rock Hard Studios - Highly welcoming entrance area for the Recording and Rehearsal Studios."
           text="Looking back towards the entrance to the Studio showing another view of the communal downstairs area"
           pageDescription=""
           dateTaken="11 January 2011"/>
  <Picture index="3"
           filename="Rock Hard Studios Blackpool Pool Table and Sofa for Bands to Chill While Recording"
           tooltip="Rock Hard Studios - The Chill Out Room complete with Comfy Sofa and Pool Table available for all bands"
           text="Upstairs at Rock Hard Studios we have a Chill Out Room with Comfy Sofa and Pool Table, as well as a shop for Sticks, Strings and Plecs."
           pageDescription=""
           dateTaken="11 January 2011"/>
  <Picture index="4"
           filename="Rock Hard Studios Blackpool Projection Cinema System and Pool Table for Bands to Enjoy during Recording Sessions"
           tooltip="Rock Hard Studios - The Chill Out Room another view showing the Cinematic Projection System and Pool Table"
           text="Another view of the Chill Out Room showing the pool table, available for all bands, and our 3m wide Cinematic Projection System"
           pageDescription=""
           dateTaken="11 January 2011"/>
  <Picture index="5"
           filename="Rock Hard Studios Blackpool Rehearsal Room Newly Refurbished Drum Kits Guitar and Bass Amp"
           tooltip="Rock Hard Studios - Newly refurbished Rehearsal Room showing the equipment included in hire"
           text="Our newly refurbished rehearsal room showing new carpet, new fender guitar amp and new pa system. Also accoustic foam on the walls."
           pageDescription=""
           dateTaken="11 January 2011"/>
  <Picture index="6"
           filename="Rock Hard Studios Blackpool Refurbished Rehearsal Room Brand New PA"
           tooltip="Rock Hard Studios - Newly refurbished rehearsal room with gear on show"
           text="A second view of our newly refurbished rehearsal rooms shows the hand made PA stand containing Feedback Suppressor, FX Reverb Unit and CD player as standard."
           pageDescription=""
           dateTaken="11 January 2011"/>
  <Picture index="7"
           filename="Rock Hard Studios Blackpool A Band Using One Of Our Three Rehearsal Rooms"
           tooltip="Rock Hard Studios - A band in full flow in a newly refurbished Rehearsal Room"
           text="This is what we're here for! A band having fun and jamming hard in a newly refurbished Rehearsal Room."
           pageDescription=""
           dateTaken="11 January 2011"/>
  <Picture index="8"
           filename="Rock Hard Studios Fun In Room 4 With A Band Rehearsing Prior to Recording"
           tooltip="Rock Hard Studios - Fun in the Studio proving it's not all about hard work"
           text="Having a laugh while rehearsing in the newly refurbished rehearsal room. Proof that being in a band is not all about hard work."
           pageDescription=""
           dateTaken="11 January 2011"/>
  <Picture index="9"
           filename="Rock Hard Studios Blackpool Newly Refurbished Control Room Available For Recording Now"
           tooltip="Rock Hard Studios - The control room newly refurbished and available for recording sessions now."
           text="The control room is now dedicated to the recording process (now the private office has been built) and looks far cleaner and tidier than our regulars will be used to. Still the same high quality kit and recording output as always though."
           pageDescription=""
           dateTaken="11 January 2011"/>
  <Picture index="10"
           filename="Rock Hard Studios Blackpool Mixing Control Surface In Recording Studio With Yamaha NS10s"
           tooltip="Rock Hard Studios - The Mixing Control Surface in the Recording studio."
           text="An arty shot of the control surface in the Control Room showing off our Yamaha NS10s and multi-screen setup for ease of use."
           pageDescription=""
           dateTaken="11 January 2011"/>
  <Picture index="11"
           filename="Rock Hard Studios Blackpool Live Room With Space for Large Bands"
           tooltip="Rock Hard Studios - Our Live Room with space for larger bands to Rehearse, as well as recording."
           text="We have also upgraded the equipment in the live room too with new amps and a new PA. Good for larger bands, obviously we also record live in here."
           pageDescription=""
           dateTaken="11 January 2011"/>
  <Picture index="12"
           filename="Rock Hard Studios Blackpool A Band Rocking in the Live Room"
           tooltip="Rock Hard Studios - A band rocking out in the Live Room, mid rehearsal"
           text="A band taking advantage of the live room rehearsal space and rocking out in 400 square feet of luxurious musical surroundings."
           pageDescription=""
           dateTaken="11 January 2011"/>
  <Picture index="13"
           filename="Rock Hard Studios Blackpool A Band Rehearsing in the Live Room"
           tooltip="Rock Hard Studios - A band rehearsing in the Live Room"
           text="Another view of the band jamming in the Live Room. Thanks to Crisi for the artwork on the wall."
           pageDescription=""
           dateTaken="11 January 2011"/>
</Pictures>
