=== rhmg/website/App_Data/Photosets/PhotoSets.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="PhotoSets"
    targetNamespace="http://www.rhmg.co.uk"
    elementFormDefault="qualified"
    xmlns="http://www.rhmg.co.uk"
    xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Pictures">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Picture" maxOccurs="unbounded" minOccurs="1">
          <xs:complexType>
            <xs:attribute name="index" type="xs:int" use="required"></xs:attribute>
            <xs:attribute name="filename" type="xs:string" use="required"></xs:attribute>
            <xs:attribute name="tooltip" type="xs:string" use="required"></xs:attribute>
            <xs:attribute name="text" type="xs:string" use="required"></xs:attribute>
            <xs:attribute name="pageDescription" type="xs:string" use="optional"></xs:attribute>
            <xs:attribute name="dateTaken" type="xs:string" use="required"></xs:attribute>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="length" type="xs:int" use="required"></xs:attribute>
      <xs:attribute name="photopath" type="xs:string" use="required"></xs:attribute>
      <xs:attribute name="pageTitle" type="xs:string" use="required"></xs:attribute>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== rhmg/website/obj/Release/Package/PackageTmp/App_Data/Photosets/PhotoshootWithNaz.xml
<?xml version="1.0" encoding="utf-8" ?>
<Pictures
  xmlns="http://www.rhmg.co.uk"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.rhmg.co.uk PhotoSets.xsd"
  length="18"
  photopath="~/images/photos/naz_session/"
  pageTitle="Photoshoot with Naz">
  <Picture index="1"
           filename="1 Karl singing his heart out at Rock Hard Studios"
           tooltip="Karl singing his heart out at Rock Hard Studios"
           text="Karl singing his heart out at Rock Hard Studios"
           pageDescription=""
           dateTaken="30 Jan 2010"/>
  <Picture index="2"
           filename="2 Karl belting a song into the Neumann TLM103 at Rock Hard Studios"
           tooltip="Karl belting a song into the Neumann TLM103 at Rock Hard Studios"
           text="Karl belting a song into the Neumann TLM103 at Rock Hard Studios"
           pageDescription=""
           dateTaken="30 Jan 2010"/>
  <Picture index="3"
           filename="3 Karl showing the passion of performing at Rock Hard Studios"
           tooltip="Karl showing the passion of performing at Rock Hard Studios"
           text="Karl showing the passion of performing at Rock Hard Studios"
           pageDescription=""
           dateTaken="30 Jan 2010"/>
  <Picture index="4"
           filename="4 Karl and a Neumann TLM103 - in perfect unison"
           tooltip="Karl and a Neumann TLM103 - in perfect unison"
           text="Karl and a Neumann TLM103 - in perfect unison"
           pageDescription=""
           dateTaken="30 Jan 2010"/>
  <Picture index="5"
           filename="5 Karl rocking out with total disregard for the consequences at Rock Hard Studios Recording Studio"
           tooltip="Karl rocking out with total disregard for the consequences at Rock Hard Studios Recording Studio"
           text="Karl rocking out with total disregard for the consequences at Rock Hard Studios Recording Studio"
           pageDescription=""
           dateTaken="30 Jan 2010"/>
  <Picture index="6"
           filename="6 Dan and Andrew recording Karl in Rock Hard Studios Recording Studio"
           tooltip="Dan and Andrew recording Karl in Rock Hard Studios Recording Studio"
           text="Dan and Andrew recording Karl in Rock Hard Studios Recording Studio"
           pageDescription=""
           dateTaken="30 Jan 2010"/>
  <Picture index="7"
           filename="7 Looking through the window from the Control Room to the Live Room at Rock Hard Studios Recording Studio"
           tooltip="Looking through the window from the Control Room to the Live Room at Rock Hard Studios Recording Studio"
           text="Looking through the window from the Control Room to the Live Room at Rock Hard Studios Recording Studio"
           pageDescription=""
           dateTaken="30 Jan 2010"/>
  <Picture index="8"
           filename="8 An arty photograph of the Digidesign C24 control surface in the Recording Studio at Rock Hard Studios"
           tooltip="An arty photograph of the Digidesign C24 control surface in the Recording Studio at Rock Hard Studios"
           text="An arty photograph of the Digidesign C24 control surface in the Recording Studio at Rock Hard Studios"
           pageDescription=""
           dateTaken="30 Jan 2010"/>
  <Picture index="9"
           filename="9 Matt warming up at Rock Hard Studios on the kit that we use to teach drums in Rock Hard Academy"
           tooltip="Matt warming up at Rock Hard Studios on the kit that we use to teach drums in Rock Hard Academy"
           text="Matt warming up at Rock Hard Studios on the kit that we use to teach drums in Rock Hard Academy"
           pageDescription=""
           dateTaken="30 Jan 2010"/>
  <Picture index="10"
           filename="10 Dan attacking the kit in the Live Room at Rock Hard Studios"
           text="Dan attacking the kit in the Live Room at Rock Hard Studios"
           tooltip="Dan attacking the kit in the Live Room at Rock Hard Studios"
           pageDescription=""
           dateTaken="30 Jan 2010"/>
  <Picture index="11"
           filename="11 Black and white of Dan laying into his cymbals on the studio kit at Rock Hard Studios"
           text="Black and white of Dan laying into his cymbals on the studio kit at Rock Hard Studios"
           tooltip="Black and white of Dan laying into his cymbals on the studio kit at Rock Hard Studios"
           pageDescription=""
           dateTaken="30 Jan 2010"/>
  <Picture index="12"
           filename="12 Dan in full flow on the drum kit at Rock Hard Studios"
           text="Dan in full flow on the drum kit at Rock Hard Studios"
           tooltip="Dan in full flow on the drum kit at Rock Hard Studios"
           pageDescription=""
           dateTaken="30 Jan 2010"/>
  <Picture index="13"
           filename="13 Dan and Karl laying down a groove in the Live Room at Rock Hard Studios"
           text="Dan and Karl laying down a groove in the Live Room at Rock Hard Studios"
           tooltip="Dan and Karl laying down a groove in the Live Room at Rock Hard Studios"
           pageDescription=""
           dateTaken="30 Jan 2010"/>
  <Picture index="14"
           filename="14 Karl playing bass at Rock Hard Studios Recording Studio"
           text="Karl playing bass at Rock Hard Studios Recording Studio"
           tooltip="Karl playing bass at Rock Hard Studios Recording Studio"
           pageDescription=""
           dateTaken="30 Jan 2010"/>
  <Picture index="15"
           filename="15 Stick on cymbal taken by Naz at Rock Hard Studios Recording Studio"
           text="Stick on cymbal taken by Naz at Rock Hard Studios Recording Studio"
           tooltip="Stick on cymbal taken by Naz at Rock Hard Studios Recording Studio"
           pageDescription=""
           dateTaken="30 Jan 2010"/>
  <Picture index="16"
           filename="16 Black and white detail of bass guitar"
           text="Black and white detail of bass guitar"
           tooltip="Black and white detail of bass guitar"
           pageDescription=""
           dateTaken="30 Jan 2010"/>
  <Picture index="17"
           filename="17 Looking through from the Live Room into the Control room with Karl reflected in the glass"
           text="Looking through from the Live Room into the Control room with Karl reflected in the glass"
           tooltip="Looking through from the Live Room into the Control room with Karl reflected in the glass"
           pageDescription=""
           dateTaken="30 Jan 2010"/>
  <Picture index="18"
           filename="18 Karl Dan and Andrew jamming in the Live Room at Rock Hard Studios"
           text="Karl Dan and Andrew jamming in the Live Room at Rock Hard Studios"
           tooltip="Karl Dan and Andrew jamming in the Live Room at Rock Hard Studios"
           pageDescription=""
           dateTaken="30 Jan 2010"/>
</Pictures>

=== rhmg/website/obj/Release/Package/PackageTmp/App_Data/Photosets/ExploreTheStudio.xml
<?xml version="1.0" encoding="utf-8" ?>
<Pictures
  xmlns="http://www.rhmg.co.uk"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.rhmg.co.uk PhotoSets.xsd"
  length="9"
  photopath="~/images/photos/explore_the_studio/"
  pageTitle="Explore The Studio">
  <Picture index="1"
           filename="Rock Hard Studios Blackpool Control Surface Digidesign Protools HD2 C24"
           tooltip="Rock Hard Studios Control Surface - Digidesign Protools HD2/C24"
           text="This is a view across the Studio Control Surface, in our custom built Control Room.  You can see our Digidesign C24 and iMac.  In the background our monitors are KRK V8s"
           pageDescription=""
           dateTaken="unknown"/>
  <Picture index="2"
           filename="Rock Hard Studios Blackpool The view from the Drum Kit"
           tooltip="Rock Hard Studios - The view from the Drum Kit"
           text="This photograph was taken just before a Rock Hard Academy drum lesson. You can see the electronic kit that Matt uses, and your view is that of one of our students. In the Control Room through the window, Andrew is pretending to work."
           pageDescription=""
           dateTaken="unknown"/>
  <Picture index="3"
           filename="Rock Hard Studios Blackpool The view from the control room into the Live Room"
           tooltip="Rock Hard Studios - The view from the control room into the Live Room"
           text="Here we are sitting on the sofa in the control room looking through our multiple-glazed window into the Live Room. You can just make out the overhead microphones over the kit through the window."
           pageDescription=""
           dateTaken="unknown"/>
  <Picture index="4"
           filename="Rock Hard Studios Blackpool The Live room viewed from the Chill Out Room"
           tooltip="Rock Hard Studios - The Live room viewed from the Chill Out Room"
           text="This photograph was taken from the window in the Chill Out Room. Here we can see the Live Room in all it's spacious glory, along with a couple of our guitar amplifiers that are available to hire."
           pageDescription=""
           dateTaken="unknown"/>
  <Picture index="5"
           filename="Rock Hard Studios Blackpool The Live room with our Drum World Custom Maple Drumkit"
           tooltip="Rock Hard Studios - The Live room with our Drum World Custom Maple Drumkit"
           text="Another view of the Live Room, this time with it set up for a rehearsal. The drum kit is our Drum World Custom Maple Drumkit."
           pageDescription=""
           dateTaken="unknown"/>
  <Picture index="6"
           filename="Rock Hard Studios Blackpool Rehearsal Room 4 including Sonor drum kit"
           tooltip="Rock Hard Studios - Rehearsal Room 4, including Sonor drum kit"
           text="One of our rehearsal rooms (specifically this is Room 4, but they are all identical) showing off the Sonor drum kit and standard double microphone set up. Notice the wall box in the back corner; This room is usable as an isolation booth for recording."
           pageDescription=""
           dateTaken="unknown"/>
  <Picture index="7"
           filename="Rock Hard Studios Blackpool Our fully stocked kitchen"
           tooltip="Rock Hard Studios - Our fully stocked kitchen"
           text="This is the room that truly sets us apart from most other studios - a well stocked and equipped kitchen that is available to all our customers."
           pageDescription=""
           dateTaken="unknown"/>
  <Picture index="8"
           filename="Rock Hard Studios Blackpool The corridor with rehearsal rooms on the left and recording studio on the right"
           tooltip="Rock Hard Studios - The corridor with rehearsal rooms on the left, and recording studio on the right"
           text="This is the view through the heart of the studio, with our rehearsal rooms down the left of the corridor, and recording suite on the right."
           pageDescription=""
           dateTaken="unknown"/>
  <Picture index="9"
           filename="Rock Hard Studios Blackpool A band enjoying a rehearsal"
           tooltip="Rock Hard Studios - A band enjoying a rehearsal"
           text="This was the very first band to ever commerically use Rock Hard Studios - Magwitch. The photograph was taken by Terry Blacow."
           pageDescription=""
           dateTaken="unknown"/>
</Pictures>
